title: liuliu (L2)
tagline: A Self-Growth Engineer, Software Engineer, Solution Architect, Software Architect, SRE
author:
  name: liuliu (L2)
  url: https://www.linkedin.com/in/chiamin-liu
social:
  name: liuliu (L2)
  links:
    - https://github.com/liuliuOD
    - https://www.linkedin.com/in/chiamin-liu
logo: /assets/images/avatar.jpg
image: /assets/images/avatar.jpg

email: liuliugit@gmail.com
description: >-
  Software Engineer | Solution Architect | Software Architect | SRE

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: liuliuod/liuliuod.github.io # for execute project in local zone

# Build settings
theme_skin: orange

sass:
  sass_dir: sass
  style: compressed

compress-site: yes
safe: false
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all

plugins:
  - jekyll-seo-tag
